
# Изучаем язык Go #24 – Ошибки

В Go существует свой подход к возвращению ошибок и их обработке. Вначале он может показаться неудобным, но когда к нему
привыкаешь – неудобным становится подход в других языках, когда просто бросаешь исключение и надеешься, что где-то оно
будет обработано.

В этом уроке мы рассмотрим как возвращать и обрабатывать ошибки.

Первый стандартный подход в работе с ошибками в Go – когда она возвращается последним значением:

```
func f1(arg int) (int, error) {
    if arg == 42 {
        return -1, errors.New("can't work with 42")
    }

    return arg + 3, nil
}
```

`errors.New()` создает ошибку с заданным сообщением. В случае успешной обработки в качестве ошибки, а точнее её
отсутствия передается `nil`

Второй стандартный подход в работе с ошибками в Go – это их явная обработка:

```
    for _, i := range []int{10, 42} {
        if r, e := f1(i); e != nil {
            fmt.Println("f1 failed:", e)
        } else {
            fmt.Println("f1 work:", r)
        }
    }
```

Выполнив такой код получим:

```
$ go run errors.go 
f1 work: 13
f1 failed: can't work with 42
```

Если при работе с исключениями в других языках на обработку исключения можно «забить», то в Go, чтобы игнорировать 
ошибку, придется явно написать `r, _ := f1(i)` и сразу будет видно, что ошибка в этом месте игнорируется.

Обратите внимание на проверку ошибки в условии `if` – такая проверка также считается стандартным подходом в языке.

Можно использовать свои структуры как ошибки. Для этого они должны реализовывать метод `Error()`. Сделаем пример такой 
структуры и продемонстрируем работу с ней:

```
type argError struct {
    arg int
    problem string
}

func (e *argError) Error() string {
    return fmt.Sprintf("%d - %s", e.arg, e.problem)
}

func f2(arg int) (int, error) {
    if arg == 42 {
        return -1, &argError{arg, "can't work with it"}
    }

    return arg + 3, nil
}
```

Код для работы с такой ошибкой будет аналогичен коду для функции `f1()`:

```
    for _, i := range []int{10, 42} {
        if r, e := f2(i); e != nil {
            fmt.Println("f2 failed:", e)
        } else {
            fmt.Println("f2 work:", r)
        }
    }
```

Выполнив этот код получим:

```
$ go run errors.go 
...
f2 work: 13
f2 failed: 42 - can't work with it
```

Если вы хотите использовать параметры пользовательской ошибки, её нужно получить следующим образом:

```
    _, e := f2(42)
    if ae, ok := e.(*argError); ok {
        fmt.Println(ae.arg)
        fmt.Println(ae.problem)
    }
```

Выполнив этот код получим:

```
$ go run errors.go 
...
42
can't work with it
```
____

В этом уроке вы узнали:

1. Как возвращать и обрабатывать ошибку
2. Какие в языке Go есть стандарты по возвращению и обработке ошибок
